language: java
sudo: required
env:
  - OS=ubuntu DIST=xenial
before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE home_dev;'
services:
  - mysql
  - docker
script:
  - ./gradlew build --info
  - touch README2.md
  - git submodule update --init --recursive
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack
deploy:
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.deb
  skip_cleanup: true
  on:
    all_branches: true
