language: java
addons:
  ssh_known_hosts: ppa.launchpad.net
before_install:
- openssl aes-256-cbc -K $encrypted_8995c04a1d4b_key -iv $encrypted_8995c04a1d4b_iv
  -in gradle/ssh/id_rsa.enc -out gradle/ssh/id_rsa -d
- cp gradle/ssh/id_rsa ~/.ssh/
- chmod 600 ~/.ssh/id_rsa
- chmod +x gradlew && mysql -e 'CREATE DATABASE home_dev;'
install:
- sudo apt-get install -y devscripts dput debhelper fakeroot python-paramiko
services:
- mysql
script: "./gradlew build --info"
skip_cleanup: true
after_success: "./gradlew replaceWords && ./gradlew debianPrepare && ./gradlew buildTar
  && ./gradlew ppaScripts"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iS8Hmp07wQxBNBKwAUmy4qIcExmVSjO9wk2CokzepsK9WRgwaF1102F00wnzCgXFUR1x+daoKSGccuHmenkvl+UifBSZYWfphTtGPvu7sNwLMKKdlY2PYVnUaJhD+aB7UrVENsSlnKdq8NSUpkeWc83izMvbPxDtffir9ZeUpyB95eVJi0sS5X0v/orSm3eV32kaFiDmWX8ZE3rFHlw0DVnRTU7/ynYdVaoh2LvG6sKWG4iZgYpsuCsLS1MF87uZq5ApV8yl6uNnEvslVDzPmfMxxjY+DiooE1c2+k1JgZdZxuJU5kAcc35C0mzCHYJ6qLvNo+J+4AdLNTJ/i42vSjdDsklmfqFsTvUOIHX+w4o0apGwvzU+e6M/cSyrOkVpIKZcKPkjJRHJLFEygcvInKwz4uI2HrT0u8mv5TVh9LN8NiT9TIi7WmgAMCc9n05EgAQT0NIp0JX+oPLGZqQxh00JZIf5FPEY70O8GzV2kIOJ3ZDRtm2Xt6B+lbun3YSgbByuvz2NLC5tSc3wKbXu2mc9PUBjmvaW10RRAhwhcA6K3GunzuHb/9cszgVhB5zGZWSW1bMIlFGQae72cBJ7lKLMMcqwA6zmWu62AEDN9dDFjfeffHXJz2fTq63rXaJZ+CAa1qf/mVwLq8nl/lXd3XOZi934LzcoWdR0fzn/uHc=
  file_glob: true
  file: build/libs/*.jar
  on:
    branches:
      only:
      - master
    repo: pvepamb1/Home-Automation
