version: '3.8'

services:
  alvis:
    image: prasennavenkatesh/homeauto
    #environment:
      # Uncomment the following if you need to connect to a local instance of a db server
      #- CONTAINER=host
      #- SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/<db_name>?useSSL=false&allowPublicKeyRetrieval=true
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      # Comment out '-db' if you are connecting to a local db server
      - db
      - ui
    networks:
      - test

  db:
    image: arm64v8/mysql:oracle
    networks:
      - test
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  ui:
    image: prasennavenkatesh/homeauto-ui
    ports:
      - "80:80"
    networks:
      - test

networks:
  test: