Document: homeauto
Title: Debian homeauto Manual
Author: <insert document author here>
Abstract: This manual describes what homeauto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/homeauto/homeauto.sgml.gz

Format: postscript
Files: /usr/share/doc/homeauto/homeauto.ps.gz

Format: text
Files: /usr/share/doc/homeauto/homeauto.text.gz

Format: HTML
Index: /usr/share/doc/homeauto/html/index.html
Files: /usr/share/doc/homeauto/html/*.html
